INSERT INTO class_label VALUES
(11, 'Fixed-wing Aircraft', 'Fixed-wing Aircraft'),
(12, 'Small Aircraft', 'Small Aircraft'),
(13, 'Cargo Plane', 'Cargo Plane'),
(15, 'Helicopter', 'Helicopter'),
(17, 'Passenger Vehicle', 'Passenger Vehicle'),
(18, 'Small Car', 'Small Car'),
(19, 'Bus', 'Bus'),
(20, 'Pickup', 'Pickup Truck'),
(21, 'Truck 7', 'Utility Truck'),
(23, 'Truck', 'Truck'),
(24, 'Truck 8', 'Cargo Truck'),
(25, 'Truck 1', 'Truck w/Box'),
(26, 'Truck 2', 'Truck Tractor'),
(27, 'Trailer', 'Trailer'),
(28, 'Truck 3', 'Truck w/Flatbed'),
(29, 'Truck 4', 'Truck w/Liquid'),
(32, 'Truck 9', 'Crane Truck'),
(33, 'Railway Vehicle', 'Railway Vehicle'),
(34, 'Passenger Car', 'Passenger Car'),
(35, 'Cargo Car', 'Cargo Car'),
(36, 'Flat Car', 'Flat Car'),
(37, 'Tank car', 'Tank car'),
(38, 'Locomotive', 'Locomotive'),
(40, 'Maritime Vessel', 'Maritime Vessel'),
(41, 'Motorboat', 'Motorboat'),
(42, 'Sailboat', 'Sailboat'),
(44, 'Tugboat', 'Tugboat'),
(45, 'Barge', 'Barge'),
(47, 'Fishing Vessel', 'Fishing Vessel'),
(49, 'Ferry', 'Ferry'),
(50, 'Yacht', 'Yacht'),
(51, 'Container Ship', 'Container Ship'),
(52, 'Oil Tanker', 'Oil Tanker'),
(53, 'Engineering Vehicle', 'Engineering Vehicle'),
(54, 'Tower crane', 'Tower crane'),
(55, 'Container Crane', 'Container Crane'),
(56, 'Reach Stacker', 'Reach Stacker'),
(57, 'Straddle Carrier', 'Straddle Carrier'),
(59, 'Mobile Crane', 'Mobile Crane'),
(60, 'Truck 5', 'Dump Truck'),
(61, 'Truck 6', 'Haul Truck'),
(62, 'Scraper', 'Scraper/Tractor'),
(63, 'Front Loader', 'Front loader/Bulldozer'),
(64, 'Excavator', 'Excavator'),
(65, 'Cement Mixer', 'Cement Mixer'),
(66, 'Ground Grader', 'Ground Grader'),
(71, 'Tent', 'Hut/Tent'),
(72, 'Shed', 'Shed'),
(73, 'Building', 'Building'),
(74, 'Aircraft Hangar', 'Aircraft Hangar'),
(76, 'Damaged Building', 'Damaged Building'),
(77, 'Facility', 'Facility'),
(79, 'Construction Site', 'Construction Site'),
(83, 'Vehicle Lot', 'Vehicle Lot'),
(84, 'Helipad', 'Helipad'),
(86, 'Storage Tank', 'Storage Tank'),
(89, 'Shipping Container Lot', 'Shipping container lot'),
(91, 'Shipping Container', 'Shipping Container'),
(93, 'Pylon', 'Pylon'),
(94, 'Tower', 'Tower');
